---
all:
  children:
    db:
      hosts:
        18.222.120.236:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /home/vcafarschi/.ssh/aws-sandbox-vcafarschi.pem
        ssh-extra-args: "-o StrictHostKeyChecking=no"



